- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: maven setup
  include_role:
    name: common
    tasks_from: maven

- name: get mysql root password
  set_fact:
    mysql_root_password: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/' + env + '/mysql/mysql_root_password', region='us-east-1', decrypt=True) }}"

- name: debug password
  debug:
    msg: "{{ mysql_root_password }}"

- name: import shipping schema
  community.mysql.mysql_db:
    name: all
    state: import
    login_host: mysql.bharath2103.site
    login_user: root
    login_password: "{{ mysql_root_password }}"
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd